name: 定时学习
on:
    workflow_dispatch:
    schedule:
        - cron: "0 12 * * 2"

jobs:
    build-and-run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Study
              env:
                  USERNAME: ${{ secrets.USERNAME }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  ORG_ID: ${{ secrets.ORG_ID }}
              run: |
                  python main.py --username $USERNAME --password $PASSWORD --org_id $ORG_ID
